[build]
  command = "npm ci && npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br, gzip"
    Content-Type = "application/javascript; charset=utf-8"
